from .auth import router as auth_router
from .user import router as user_router
from .role import router as role_router
from .province import router as province_router
from .district import router as district_router
from .subdistrict import router as subdistrict_router
from .narcotic import router as narcotic_router
from .drug_form import router as drug_form_router
from .exhibit import router as exhibit_router
from .inference import router as inference_router
from .vector import router as vector_router
from .history import router as history_router